const STORAGE_KEYS = {
  balance: "ahita.cookies.balance",
  sessionId: "ahita.forestlife.sessionId",
  broughtIn: "ahita.forestlife.broughtIn",
  spent: "ahita.forestlife.spent",
  state: "ahita.forestlife.state"
};
const SNACK_COST_PER_ANIMAL = 1;
const ACTIONS_PER_DAY = 2;
const TOAST_DURATION_MS = 1600;
const WORK_PLANS = [{ id: "gather_leaves", unlockDay: 1, rewardAmount: 2 }];
const BLACK_MARKET_ITEMS = [
  { id: "black_cookie", label: "黒いクッキー", buyCost: 6, sellPrice: 9, uneaseGain: 1, riskLevel: 1 },
  { id: "very_tasty_cookie", label: "すごくおいしいクッキー", buyCost: 10, sellPrice: 16, uneaseGain: 2, riskLevel: 2 },
  { id: "cookie_question", label: "クッキー？", buyCost: 14, sellPrice: 25, uneaseGain: 4, riskLevel: 3 }
];
const BASE_RECEIVABLE_DEFAULT = { 1: 0.1, 2: 0.18, 3: 0.3 };
const PLANS = { lend:[{ id:"lend-small", unlockDay:1, cost:4, dueDays:2, returnAmount:7, shortLabel:"短くあずける", detailLabel:"-4 / 2日後 +7" },{ id:"lend-mid", unlockDay:5, cost:7, dueDays:5, returnAmount:13, shortLabel:"しばらくあずける", detailLabel:"-7 / 5日後 +13" },{ id:"lend-large", unlockDay:10, cost:10, dueDays:10, returnAmount:20, shortLabel:"長くあずける", detailLabel:"-10 / 10日後 +20" }], borrow:[{ id:"borrow-small", unlockDay:1, gain:5, dueDays:2, repayAmount:7, shortLabel:"少し前借り", detailLabel:"+5 / 2日後 -7" },{ id:"borrow-mid", unlockDay:5, gain:9, dueDays:5, repayAmount:14, shortLabel:"しばらく前借り", detailLabel:"+9 / 5日後 -14" },{ id:"borrow-large", unlockDay:10, gain:15, dueDays:10, repayAmount:25, shortLabel:"長く前借り", detailLabel:"+15 / 10日後 -25" }], invest:[{ id:"invest-small", type:"instant_risk", unlockDay:1, cost:3, successRate:0.65, successReturn:7, failReturn:0, shortLabel:"小さな話", detailLabel:"-3 / 65%で +7" },{ id:"invest-mid", type:"instant_risk", unlockDay:5, cost:6, successRate:0.5, successReturn:14, failReturn:0, shortLabel:"うまそうな話", detailLabel:"-6 / 50%で +14" },{ id:"invest-large", type:"instant_risk", unlockDay:10, cost:10, successRate:0.35, successReturn:28, failReturn:0, shortLabel:"大きな話", detailLabel:"-10 / 35%で +28" },{ id:"dividend-panda", type:"dividend_like", unlockDay:5, cost:8, dailyDividend:3, bankruptcyRate:0.2, shortLabel:"パンダ組合の話", detailLabel:"-8 / 毎日 +3 / 倒産しやすい" },{ id:"dividend-koguma", type:"dividend_like", unlockDay:5, cost:7, dailyDividend:2, bankruptcyRate:0.08, shortLabel:"コグマ商会の話", detailLabel:"-7 / 毎日 +2 / 倒産しにくい" }]};
const MILESTONE_UNLOCKS={5:["新しいあずけ先が見つかりました"],10:["夜の市場のうわさを聞きました"],15:["さらに深い森のうわさが流れています"]};
const dom = { startScreen:document.getElementById("forest-life-start-screen"), gameScreen:document.getElementById("forest-life-game-screen"), resultScreen:document.getElementById("forest-life-result-screen"), balanceEl:document.getElementById("forest-balance"), broughtInInput:document.getElementById("brought-in-input"), startButton:document.getElementById("start-forest-session"), dayEl:document.getElementById("forest-day"), statusEl:document.getElementById("forest-session-status"), snackCostEl:document.getElementById("forest-snack-cost"), actionsLeftEl:document.getElementById("forest-actions-left"), animalsEl:document.getElementById("forest-animals"), dayStatusEl:document.getElementById("forest-day-status"), workButton:document.getElementById("forest-work-button"), lendButton:document.getElementById("forest-lend-button"), borrowButton:document.getElementById("forest-borrow-button"), investButton:document.getElementById("forest-invest-button"), nextDayButton:document.getElementById("forest-next-day-button"), finishButton:document.getElementById("finish-forest-session"), blackMarketHint:document.getElementById("forest-black-market-hint"), blackMarketButton:document.getElementById("forest-black-market-button"), blackMarketPanel:document.getElementById("forest-black-market-panel"), blackMarketActions:document.getElementById("forest-black-market-actions"), uneaseEl:document.getElementById("forest-unease"), trustEl:document.getElementById("forest-black-market-trust"), inventoryList:document.getElementById("forest-black-market-inventory"), arList:document.getElementById("forest-accounts-receivable"), apList:document.getElementById("forest-accounts-payable"), factorySummary:document.getElementById("forest-factory-summary"), factoryButton:document.getElementById("forest-build-factory-button"), lendList:document.getElementById("forest-lend-list"), borrowList:document.getElementById("forest-borrow-list"), dividendList:document.getElementById("forest-dividend-list"), investLog:document.getElementById("forest-invest-log"), actionLog:document.getElementById("forest-action-log"), actionPlanPanel:document.getElementById("forest-action-plan-panel"), actionPlanTitle:document.getElementById("forest-action-plan-title"), actionPlanList:document.getElementById("forest-action-plan-list"), closePlanPanelButton:document.getElementById("forest-close-plan-panel"), resultTitle:document.getElementById("forest-result-title"), resultBroughtIn:document.getElementById("forest-result-brought-in"), resultDay:document.getElementById("forest-result-day"), resultBalance:document.getElementById("forest-result-balance"), resultLending:document.getElementById("forest-result-lending"), resultBorrowing:document.getElementById("forest-result-borrowing"), retryButton:document.getElementById("forest-retry-button"), toast:document.getElementById("forest-life-toast") };
let safeStorage=null,forestLifeBgm=null,forestLifeBgmToggle=null,selectedActionCategory=null,forestToastTimer=null;
const safeInt=(v,f=0)=>{const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.floor(n)):f;};
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
const clampRate=(v,min,max)=>clamp(v,min,max);
const getAnimalsForDay=(day,resetDay)=>{const base = safeInt(resetDay,0)>0 ? Math.max(0,safeInt(day,1)-safeInt(resetDay,0)) : Math.max(1,safeInt(day,1))-1;return Math.max(1,1+Math.floor(base/3));};
const getDailySnackCost=(state)=>getAnimalsForDay(state.day,state.animalResetDay)*SNACK_COST_PER_ANIMAL + Math.floor((state.forestUnease||0)/8);
const newState=()=>({version:3,status:"idle",day:0,broughtIn:0,hand:0,totalSnackPaid:0,actionsLeft:ACTIONS_PER_DAY,animals:1,lends:[],borrows:[],investReturns:[],dividendInvestments:[],investResults:[],actionLogs:[],tired:false,unlockedMilestones:[],forestUnease:0,blackMarketTrust:50,blackMarketInventory:[],accountsReceivable:[],accountsPayable:[],cookieFactories:[],reincarnationCount:0,animalResetDay:0,blackMarketUsedToday:false});
const appendLog=(s,m)=>{s.actionLogs.unshift(`Day${s.day}: ${m}`);s.actionLogs=s.actionLogs.slice(0,60);};
const itemById=(id)=>BLACK_MARKET_ITEMS.find((x)=>x.id===id);
function showForestToast(m){if(!dom.toast)return;dom.toast.textContent=m;dom.toast.hidden=false;dom.toast.classList.add("is-visible");if(forestToastTimer)clearTimeout(forestToastTimer);forestToastTimer=setTimeout(()=>{dom.toast.classList.remove("is-visible");dom.toast.hidden=true;},TOAST_DURATION_MS);}
function loadForestLifeState(){if(!safeStorage)return newState();let p=null;try{p=JSON.parse(safeStorage.getItem(STORAGE_KEYS.state)||"null");}catch{}const b=newState();if(!p||typeof p!=="object")return b;Object.assign(b,p);b.forestUnease=safeInt(p.forestUnease,0);b.blackMarketTrust=clamp(safeInt(p.blackMarketTrust,50),0,100);b.blackMarketInventory=Array.isArray(p.blackMarketInventory)?p.blackMarketInventory:[];b.accountsReceivable=Array.isArray(p.accountsReceivable)?p.accountsReceivable:[];b.accountsPayable=Array.isArray(p.accountsPayable)?p.accountsPayable:[];b.cookieFactories=Array.isArray(p.cookieFactories)?p.cookieFactories:[];b.reincarnationCount=safeInt(p.reincarnationCount,0);b.animalResetDay=safeInt(p.animalResetDay,0);b.animals=getAnimalsForDay(b.day,b.animalResetDay);return b;}
const saveForestLifeState=(s)=>safeStorage&&safeStorage.setItem(STORAGE_KEYS.state,JSON.stringify(s));
const consumeAction=(s)=>{s.actionsLeft=Math.max(0,s.actionsLeft-1);if(s.actionsLeft===0)s.tired=true;};
function getEffectiveReceivableDefaultChance(item,s){const base=BASE_RECEIVABLE_DEFAULT[item.riskLevel]||0.12;return clampRate(base+s.forestUnease*0.01-s.blackMarketTrust*0.002,0.05,0.6);} 
function getEffectivePayableEscapeChance(_,s){return clampRate(0.25+s.forestUnease*0.01-s.blackMarketTrust*0.002,0.05,0.5);} 
function applyAccountsReceivable(s){s.accountsReceivable=s.accountsReceivable.filter((r)=>{if(r.dueDay>s.day)return true;const item=itemById(r.itemId)||{label:r.label,riskLevel:1};if(Math.random()<getEffectiveReceivableDefaultChance(item,s)){s.blackMarketTrust=clamp(s.blackMarketTrust-2,0,100);s.forestUnease+=1;appendLog(s,`${item.label}の売掛は、朝になっても届きませんでした。`);}else{s.hand+=safeInt(r.amount,0);s.blackMarketTrust=clamp(s.blackMarketTrust+1,0,100);appendLog(s,`売掛の約束どおり、${item.label}の代金${r.amount}枚が届きました。`);}return false;});}
function applyAccountsPayable(s){s.accountsPayable=s.accountsPayable.filter((p)=>{if(p.dueDay>s.day)return true;if(s.hand>=p.amount){s.hand-=p.amount;s.blackMarketTrust=clamp(s.blackMarketTrust+1,0,100);appendLog(s,`買掛の支払いとして${p.amount}枚を渡しました。`);return false;}if(Math.random()<getEffectivePayableEscapeChance(p,s)){s.blackMarketTrust=clamp(s.blackMarketTrust-1,0,100);s.forestUnease+=1;appendLog(s,"買掛の帳面は、なぜか白紙になっていました。");return false;}p.amount+=safeInt(p.interestOnFailure,2);p.dueDay+=2;s.blackMarketTrust=clamp(s.blackMarketTrust-4,0,100);s.forestUnease+=2;appendLog(s,"買掛の支払いは残りました。利息がつき、次の夜へ持ち越されました。");return true;});}
function applyCookieFactoryDividend(s){const count=s.cookieFactories.length;if(count<=0)return;s.hand+=count;appendLog(s,`クッキー工場から配当として${count}枚届きました。`);} 
function sellCookieFactory(){showForestToast("工場を売る話は、まだ誰にも切り出せません。");}
function beginDay(s){if(s.status!=="playing")return;s.day+=1;s.actionsLeft=ACTIONS_PER_DAY;s.tired=false;s.animals=getAnimalsForDay(s.day,s.animalResetDay);s.lends=s.lends.filter(i=>i.day!==s.day||(s.hand+=i.amount,false));s.borrows=s.borrows.filter(i=>i.day!==s.day||(s.hand-=i.amount,false));s.investReturns=s.investReturns.filter(i=>i.day!==s.day||(s.hand+=i.amount,false));s.dividendInvestments=s.dividendInvestments.filter((inv)=>{if(Math.random()<Number(inv.bankruptcyRate||0)+s.forestUnease*0.002)return false;s.hand+=safeInt(inv.dailyDividend,0);return true;});applyAccountsReceivable(s);applyAccountsPayable(s);applyCookieFactoryDividend(s);const snack=getDailySnackCost(s);s.hand-=snack;s.totalSnackPaid+=snack;appendLog(s,`今日のおやつ代として${snack}枚使いました。`);if(s.hand<=0){s.status="ended";s.tired=true;appendLog(s,"クッキーが尽きた。静かな夜が来る。");return;}s.blackMarketUsedToday=false;}
function doWork(s){if(s.actionsLeft<=0)return;s.hand+=2;appendLog(s,"森で働いて、クッキーを2枚受け取りました。");consumeAction(s);} 
function doBlackMarketBuy(s,item,payLater){if(s.actionsLeft<=0)return;if(!payLater&&s.hand<item.buyCost)return;if(payLater&&s.blackMarketTrust<35)return appendLog(s,"夜の信用が足りず、買掛の話はまとまりませんでした。");if(!payLater){s.hand-=item.buyCost;}else{s.accountsPayable.push({id:crypto.randomUUID(),itemId:item.id,dueDay:s.day+3,amount:item.buyCost+2,interestOnFailure:2,label:item.label});}s.blackMarketInventory.push({itemId:item.id,label:item.label});consumeAction(s);} 
function doBlackMarketSell(s,item,sellLater){if(s.actionsLeft<=0)return;const idx=s.blackMarketInventory.findIndex((x)=>x.itemId===item.id);if(idx<0)return;s.blackMarketInventory.splice(idx,1);if(!sellLater){s.hand+=item.sellPrice;}else{s.accountsReceivable.push({id:crypto.randomUUID(),itemId:item.id,dueDay:s.day+3,amount:item.sellPrice+2,label:item.label});}s.forestUnease+=item.uneaseGain;consumeAction(s);} 
function buildCookieFactory(s){if(s.hand<50)return;s.hand-=50;s.cookieFactories.push({id:crypto.randomUUID(),builtDay:s.day});s.reincarnationCount+=1;s.animalResetDay=s.day;s.animals=getAnimalsForDay(s.day,s.animalResetDay);appendLog(s,"クッキー工場を建てました。これまで養っていた動物たちは、そこで自分たちのおやつをまかなうようになりました。");appendLog(s,"今日から、また1匹の動物におやつを用意します。");showForestToast("クッキー工場を建てました");}
function renderList(el,rows,empty){if(!el)return;el.innerHTML="";if(!rows.length){const li=document.createElement("li");li.textContent=empty;el.appendChild(li);return;}rows.forEach((r)=>{const li=document.createElement("li");li.textContent=r;el.appendChild(li);});}
function renderBlackMarketPanel(s){if(!dom.blackMarketPanel)return;dom.blackMarketPanel.hidden=s.day<10||s.status!=="playing";if(dom.uneaseEl)dom.uneaseEl.textContent=`森のざわめき: ${safeInt(s.forestUnease,0)}`;if(dom.trustEl)dom.trustEl.textContent=`夜の信用: ${safeInt(s.blackMarketTrust,50)}`;renderList(dom.inventoryList,s.blackMarketInventory.map((x)=>x.label),"夜の在庫はまだありません。");renderList(dom.arList,s.accountsReceivable.map((x)=>`${x.label}: ${x.dueDay}日目に${x.amount}枚`),"受け取る約束はありません。");renderList(dom.apList,s.accountsPayable.map((x)=>`${x.label}: ${x.dueDay}日目に${x.amount}枚`),"支払う約束はありません。");const fc=s.cookieFactories.length;dom.factorySummary.textContent=fc?`所有数: ${fc} / 毎日の配当: +${fc}`:"クッキー工場はまだありません。";dom.factoryButton.hidden=s.hand<50;dom.blackMarketActions.innerHTML="";BLACK_MARKET_ITEMS.forEach((item)=>{const mk=(label,fn)=>{const b=document.createElement("button");b.type="button";b.textContent=label;b.disabled=s.actionsLeft<=0;b.onclick=()=>{const st=loadForestLifeState();fn(st);saveForestLifeState(st);renderForestLife();};dom.blackMarketActions.appendChild(b);};mk(`${item.label}を仕入れる -${item.buyCost} / 在庫+1`,(st)=>doBlackMarketBuy(st,item,false));mk(`${item.label}を買掛で仕入れる 在庫+1 / 3日後-${item.buyCost+2}`,(st)=>doBlackMarketBuy(st,item,true));mk(`${item.label}を売る +${item.sellPrice} / ざわめき+${item.uneaseGain}`,(st)=>doBlackMarketSell(st,item,false));mk(`${item.label}を売掛で売る 3日後+${item.sellPrice+2}`,(st)=>doBlackMarketSell(st,item,true));});}
function renderForestLife(){const s=loadForestLifeState();dom.balanceEl.textContent=`現在のフォレストクッキー残高: ${safeInt(loadCookieBalance(),0)}`;dom.startScreen.hidden=s.status!=="idle";dom.gameScreen.hidden=s.status!=="playing";dom.resultScreen.hidden=s.status!=="ended";if(s.status==="playing"){s.animals=getAnimalsForDay(s.day,s.animalResetDay);dom.dayEl.textContent=`現在の日数: ${s.day}日目`;dom.statusEl.textContent=`手持ちクッキー: ${Math.max(0,safeInt(s.hand,0))}`;dom.snackCostEl.textContent=`今日のおやつ代: ${getDailySnackCost(s)}枚`;dom.actionsLeftEl.textContent=`今日の残り行動回数: ${s.actionsLeft}回`;dom.animalsEl.textContent=`おやつを待つ動物たち: ${s.animals}匹`;dom.dayStatusEl.textContent=s.actionsLeft===0?"今日はもうくたくたです。明日にしましょう。":"森は静かです。次の行動を選んでください。";dom.blackMarketHint.hidden=s.day<10;dom.blackMarketButton.textContent=s.day>=10?"夜の市場を開く（闇市商人）":"夜の市場をのぞく（まだ入れない）";renderBlackMarketPanel(s);dom.nextDayButton.disabled=!s.tired;renderList(dom.lendList,s.lends.map((x)=>`${x.day}日目に ${x.amount}枚 返却予定`),"予約中の貸付はありません。");renderList(dom.borrowList,s.borrows.map((x)=>`${x.day}日目に ${x.amount}枚 返済予定`),"返済予定の借り入れはありません。");renderList(dom.investLog,s.investResults||[],"投資ログはまだありません。");renderList(dom.actionLog,s.actionLogs||[],"行動ログはまだありません。");}
if(s.status==="ended"){dom.resultTitle.textContent=`森で${s.day}日分のおやつをまかなえました`;dom.resultBroughtIn.textContent=`持ち込んだクッキー数: ${s.broughtIn}`;dom.resultDay.textContent=`最終日数: ${s.day}`;dom.resultBalance.textContent=`最後の手持ちクッキー: ${Math.max(0,s.hand)}`;dom.resultLending.textContent=`貸付中だったクッキー数: ${s.lends.reduce((a,b)=>a+b.amount,0)+s.investReturns.reduce((a,b)=>a+b.amount,0)}`;dom.resultBorrowing.textContent=`返済予定だったクッキー数: ${s.borrows.reduce((a,b)=>a+b.amount,0)}`;}}
function startForestLifeGame(){const bal=safeInt(safeStorage.getItem(STORAGE_KEYS.balance),0),inb=safeInt(dom.broughtInInput.value,0);if(inb<=0||inb>bal)return;const s=newState();s.status="playing";s.broughtIn=inb;s.hand=inb;safeStorage.setItem(STORAGE_KEYS.balance,String(bal-inb));beginDay(s);saveForestLifeState(s);renderForestLife();}
function resetForestLifeGame(){selectedActionCategory=null;saveForestLifeState(newState());renderForestLife();}
safeStorage=localStorage;if(!safeStorage.getItem(STORAGE_KEYS.state))saveForestLifeState(newState());renderForestLife();
dom.startButton.addEventListener("click",startForestLifeGame);dom.workButton.addEventListener("click",()=>{const s=loadForestLifeState();doWork(s);saveForestLifeState(s);renderForestLife();});dom.nextDayButton.addEventListener("click",()=>{const s=loadForestLifeState();if(!s.tired)return;beginDay(s);saveForestLifeState(s);renderForestLife();});dom.blackMarketButton.addEventListener("click",()=>{const s=loadForestLifeState();if(s.day<10){appendLog(s,"入口は見えますが、今日はまだ入れません。");saveForestLifeState(s);}renderForestLife();});dom.factoryButton&&dom.factoryButton.addEventListener("click",()=>{const s=loadForestLifeState();buildCookieFactory(s);saveForestLifeState(s);renderForestLife();});dom.retryButton.addEventListener("click",resetForestLifeGame);dom.finishButton.addEventListener("click",()=>{window.location.href="index.html"});
forestLifeBgm=document.getElementById("forest-life-bgm");forestLifeBgmToggle=document.getElementById("forest-life-bgm-toggle");if(forestLifeBgm)forestLifeBgm.volume=.35;forestLifeBgmToggle&&forestLifeBgmToggle.addEventListener("click",async()=>{if(forestLifeBgm.paused){try{await forestLifeBgm.play();}catch{}}else{forestLifeBgm.pause();}forestLifeBgmToggle.textContent=forestLifeBgm.paused?"BGMを流す":"BGMを止める";forestLifeBgmToggle.setAttribute("aria-pressed",forestLifeBgm.paused?"false":"true");});
